#! /usr/bin/env bash

set -e

if [ -f "package.json" ]; then
    version=$(jq -r '.version' package.json)
    echo $version
else 
    echo "`package.json` not found in this directory"
    exit 1
fi

build_number="7"
version_str="${version}-${build_number}-preview"
 
git config user.name github-actions
git config user.email github-actions@github.com
git tag -a "${version_str}" -m "${version_str}"
git push --tags
echo "Tagging completed!"