name: Test Repo Build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  version_bump:
    permissions:
      contents: write
    name: "Bump Version on develop"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: develop
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version patch
          git push -u origin develop
          git push --tags
  tag_release:
    needs: [version_bump]
    permissions:
      contents: write
    name: "Tag new release"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v4"
        with:
          ref: main
      - name: "🏷️ Create new git tag"
        run: ./scripts/tag-release
